### ISSUE TITLE
No issues just a question

### ISSUE THREAD

**Issue by Artistblock307** [vitormhenrique/xbox_chatpad_library#2]
Hi, I was wondering if I could use this as ps/2 keyboard?
I need it for a project that normally uses a old school keyboard for ascii input. 

So, just asking, the schematic mentions a clock and data pin from the keyboard but the chatpad has a rx and tx line. would it be compatible? 

Or would I need to switch out the libraries in the sketch?

**Comment by vitormhenrique** [comment]
You can definitely substitute a ps/2 keyboard with this... it is a cheap little neat solution...
I'm using it to control a bitlash mini notebook, check the keyboard test here: https://youtu.be/nhJnCoi3czc

Keep in mind that because it is not a full size keyboard it is not as easy to input data, if you need speed, keep a old full size keyboard.

Which schematic mentions a clock and data pin? chatpad uses serial communication, there is nothing you need to change inside the example sketch. If you are using a very fast microcontroller (like teensy) you may need to add a delay on the start up routine, chatpad take few milliseconds to boot, and if you start the communication before this you will only receive garbage from the serial port, arduinos unos and megas dont have this problem because their boot time is pretty slow.

**Comment by Artistblock307** [comment]
Oh yeah, I saw that!  Nice work.

But what I really want to know is which is which? the pinouts of the chatpad are, TX, RX, V+,V-. The power pins are simple enough but what are data and clock, tx or rx?

Also since you got a teensy to run bitlash i was wondering is it possible to use a arduino uno because there's no tvout support for the teensy.

**Comment by vitormhenrique** [comment]
You need to solder wires to the bottom of the pcb on chatpad following this pinout
http://cliffle.com/project/chatpad/pinout/

You can also use the conector if you want to. 
Connect the RX from chatpad to the TX on arduino (pin 1) and TX from chatpad on RX on arduino (pin 0)

There are some test points on chatpad that makes the solder job easy, just be carefull while desoldering the cable connector if you do that. you can easly remove the copper on the pads.

The lirary is going to work fine on uno. But instead of using a TV why won't you use a LCD? or OLED?

**Comment by Artistblock307** [comment]
Thanks I figured as much. And about the screen I found out that arduino can only display monotone graphics too late so I bought a small composite lcd. Besides if I ever buy a raspberry pi I can use it as wireless screen with a $10 video transmitter(the kind used with rear view car cameras) and there are some fun things you can do with composite video http://nootropicdesign.com/ve/
